In [ ]:
import torch

In [ ]:
x = torch.tensor([[[1, 2],
                    [3, 4]],
                  [[5, 6],
                  [7, 8]],
                  [[9, 10],
                  [11, 12]]]
                )

In [ ]:
x.shape

torch.Size([3, 2, 2])

In [ ]:
print(x.dim())

3


In [ ]:
x.reshape(2, -1), x.reshape(2, -1).shape

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 torch.Size([2, 6]))

In [ ]:
x.reshape(3, -1), x.reshape(3, -1).shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [ ]:
x.size()

torch.Size([3, 2, 2])

In [ ]:
x.view(2, -1), x.view(2, -1).size()

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 torch.Size([2, 6]))

In [ ]:
x.view(3, -1), x.view(3, -1).size()

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))