# Tensor shape, axis

## numpy.ndarray

In [ ]:
import numpy as np

### Scalar (Number)

In [ ]:
x = np.array(5)

In [ ]:
print(x)
print(type(x))
print('rank : ', x.ndim)
print('shape : ', x.shape)

5
<class 'numpy.ndarray'>
rank :  0
shape :  ()


### Vector

In [ ]:
x = np.array([1,2,3,5])

In [ ]:
print(x)
print(type(x))
print('rank : ', x.ndim)
print('shape : ', x.shape)

[1 2 3 5]
<class 'numpy.ndarray'>
rank :  1
shape :  (4,)


### Matrix

In [ ]:
x = np.array([
               [1,2,3,5],
               [4,5,6,7]
             ])

In [ ]:
print(x)
print(type(x))
print('rank : ', x.ndim)
print('shape : ', x.shape)

[[1 2 3 5]
 [4 5 6 7]]
<class 'numpy.ndarray'>
rank :  2
shape :  (2, 4)


### Tensor

In [ ]:
x = np.array([  # (3, 2, 4)
               [
                 [1,2,3,5],
                 [4,5,6,9]
               ],
               [
                 [7,8,9,1],
                 [1,7,2,6]
               ],
               [
                 [7,8,9,1],
                 [1,7,2,6]
               ]
            ])


In [ ]:
print(x)
print(type(x))
print('rank : ', x.ndim)
print('shape : ', x.shape)

[[[1 2 3 5]
  [4 5 6 9]]

 [[7 8 9 1]
  [1 7 2 6]]

 [[7 8 9 1]
  [1 7 2 6]]]
<class 'numpy.ndarray'>
rank :  3
shape :  (3, 2, 4)


## torch.Tensor

In [ ]:
import torch

In [ ]:
x = torch.tensor([
               [1,2,3,5],
               [4,5,6,7]
             ])
x

tensor([[1, 2, 3, 5],
        [4, 5, 6, 7]])

In [ ]:
print(x)
print(type(x))
print('rank : ', x.ndim)
print('shape : ', x.shape)

tensor([[1, 2, 3, 5],
        [4, 5, 6, 7]])
<class 'torch.Tensor'>
rank :  2
shape :  torch.Size([2, 4])


### numpy to torch

In [ ]:
import numpy as np
import torch

# numpy array creation
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print(numpy_array)
print(type(numpy_array))

# numpy to torch tesnor
torch_tensor = torch.from_numpy(numpy_array)

print(torch_tensor)
print(type(torch_tensor))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>


### torch to numpy

In [ ]:
import torch

# torch tensor
torch_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(torch_tensor)
print(type(torch_tensor))
print('rank : ', torch_tensor.ndim)
print('shape : ', torch_tensor.shape)

# torch tensor to numpy array
numpy_array = torch_tensor.numpy()

print(numpy_array)
print(type(numpy_array))
print('rank : ', numpy_array.ndim)
print('shape : ', numpy_array.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>
rank :  2
shape :  torch.Size([2, 3])
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
rank :  2
shape :  (2, 3)
